#! /usr/bin/perl

=head1 NAME

B<squidtoapachecombinedlog>

=head1 DESCRIPTION

Convert the default squid access log to apache combined log

=head1 SYNOPSIS

B<squidtoapachecombinedlog> /var/log/squid/access.log

B<squidtoapachecombinedlog> /var/log/squid/access.log.1.gz

tail /var/log/squid/access.log | B<squidtoapachecombinedlog>

=cut

use IO::File;
use POSIX qw(strftime);

my $GUNZIP='/bin/gunzip';
my ($fh,$log,$te,$sourceip,$squidcomb1,$size,$method,$url,$user,$squidcomb2);
my ($mimetype,$lastlog,$http_protocol,$refer,$useragent,$apachetime,$squid_req_status);
my ($http_status_code,$squid_hierarchy_status,$source_FQDN);

usage() if $ARGV[0] && ! -e $ARGV[0];
$fh = new IO::Handle;
if ($ARGV[0]=~/\.gz$/) {
 $fh = new IO::File("$GUNZIP -c $ARGV[0] |") or usage("ERR: ($GUNZIP | $ARGV[0]) $!")
}
elsif($ARGV[0]) {
 $fh = new IO::File($ARGV[0]) or usage($!);
}
else {
 $fh->fdopen(fileno(STDIN),"r") or usage($!);
}
while ($log=<$fh>) {
  if ($log=~/^(\d+\.\d+) +\d+ ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) *(.+)*$/) {
    ($te,$sourceip,$squidcomb1,$size,$method,$url,$user,$squidcomb2,$mimetype,$lastlog)=($1,$2,$3,$4,$5,$6,$7,$8,$9,$10);
    if ($lastlog=~/^([^ ]+) "([^"]+)" "([^"]+)"/) {
       ($http_protocol,$refer,$useragent)=($1,$2,$3);
    }
    else { 
      $http_protocol='HTTP/1.1';
      $refer,$useragent='';
    }
    $http_protocol='HTTP/'.$http_protocol if $http_protocol=~/^\d/;
    $apachetime=strftime("[%d/%b/%Y:%H:%M:%S %z]", localtime($te));
    ($squid_req_status,$http_status_code)=split(/\//,$squidcomb1);
    ($squid_hierarchy_status,$source_FQDN)=split(/\//,$squidcomb2);
    print qq|$sourceip - $user $apachetime "$method $url $http_protocol" $http_status_code $size "$refer" "$useragent" $squid_req_status:$squid_hierarchy_status\n|;
  }
}
close $fh;
exit;

sub usage {
 print "@_\n" if @_;
 print qq|
 Usare: $0 [file_squid_log]
  file_squid_log may be compressed in .gz (file_squid_log.gz).
  You may use this as a filter reading to the standard input
 |;
 exit 1;
}

=head1 COPYRIGHT

squidtoapachecombinedlog is Copyright (c) 2014 Enio Carboni - Italy

squidtoapachecombinedlog is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

squidtoapachecombinedlog is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with offline. If not, see <http://www.gnu.org/licenses/>.

=head1 SUPPORT / WARRANTY

The squidtoapachecombinedlog is free Open Source software. IT COMES WITHOUT WARRANTY OF ANY KIND.

